require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GpDiagnosesController do

  # This should return the minimal set of attributes required to create a valid
  # GpDiagnosis. As you add validations to GpDiagnosis, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GpDiagnosesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all gp_diagnoses as @gp_diagnoses" do
      gp_diagnosis = GpDiagnosis.create! valid_attributes
      get :index, {}, valid_session
      assigns(:gp_diagnoses).should eq([gp_diagnosis])
    end
  end

  describe "GET show" do
    it "assigns the requested gp_diagnosis as @gp_diagnosis" do
      gp_diagnosis = GpDiagnosis.create! valid_attributes
      get :show, {:id => gp_diagnosis.to_param}, valid_session
      assigns(:gp_diagnosis).should eq(gp_diagnosis)
    end
  end

  describe "GET new" do
    it "assigns a new gp_diagnosis as @gp_diagnosis" do
      get :new, {}, valid_session
      assigns(:gp_diagnosis).should be_a_new(GpDiagnosis)
    end
  end

  describe "GET edit" do
    it "assigns the requested gp_diagnosis as @gp_diagnosis" do
      gp_diagnosis = GpDiagnosis.create! valid_attributes
      get :edit, {:id => gp_diagnosis.to_param}, valid_session
      assigns(:gp_diagnosis).should eq(gp_diagnosis)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GpDiagnosis" do
        expect {
          post :create, {:gp_diagnosis => valid_attributes}, valid_session
        }.to change(GpDiagnosis, :count).by(1)
      end

      it "assigns a newly created gp_diagnosis as @gp_diagnosis" do
        post :create, {:gp_diagnosis => valid_attributes}, valid_session
        assigns(:gp_diagnosis).should be_a(GpDiagnosis)
        assigns(:gp_diagnosis).should be_persisted
      end

      it "redirects to the created gp_diagnosis" do
        post :create, {:gp_diagnosis => valid_attributes}, valid_session
        response.should redirect_to(GpDiagnosis.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved gp_diagnosis as @gp_diagnosis" do
        # Trigger the behavior that occurs when invalid params are submitted
        GpDiagnosis.any_instance.stub(:save).and_return(false)
        post :create, {:gp_diagnosis => {}}, valid_session
        assigns(:gp_diagnosis).should be_a_new(GpDiagnosis)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GpDiagnosis.any_instance.stub(:save).and_return(false)
        post :create, {:gp_diagnosis => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested gp_diagnosis" do
        gp_diagnosis = GpDiagnosis.create! valid_attributes
        # Assuming there are no other gp_diagnoses in the database, this
        # specifies that the GpDiagnosis created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GpDiagnosis.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => gp_diagnosis.to_param, :gp_diagnosis => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested gp_diagnosis as @gp_diagnosis" do
        gp_diagnosis = GpDiagnosis.create! valid_attributes
        put :update, {:id => gp_diagnosis.to_param, :gp_diagnosis => valid_attributes}, valid_session
        assigns(:gp_diagnosis).should eq(gp_diagnosis)
      end

      it "redirects to the gp_diagnosis" do
        gp_diagnosis = GpDiagnosis.create! valid_attributes
        put :update, {:id => gp_diagnosis.to_param, :gp_diagnosis => valid_attributes}, valid_session
        response.should redirect_to(gp_diagnosis)
      end
    end

    describe "with invalid params" do
      it "assigns the gp_diagnosis as @gp_diagnosis" do
        gp_diagnosis = GpDiagnosis.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GpDiagnosis.any_instance.stub(:save).and_return(false)
        put :update, {:id => gp_diagnosis.to_param, :gp_diagnosis => {}}, valid_session
        assigns(:gp_diagnosis).should eq(gp_diagnosis)
      end

      it "re-renders the 'edit' template" do
        gp_diagnosis = GpDiagnosis.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GpDiagnosis.any_instance.stub(:save).and_return(false)
        put :update, {:id => gp_diagnosis.to_param, :gp_diagnosis => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested gp_diagnosis" do
      gp_diagnosis = GpDiagnosis.create! valid_attributes
      expect {
        delete :destroy, {:id => gp_diagnosis.to_param}, valid_session
      }.to change(GpDiagnosis, :count).by(-1)
    end

    it "redirects to the gp_diagnoses list" do
      gp_diagnosis = GpDiagnosis.create! valid_attributes
      delete :destroy, {:id => gp_diagnosis.to_param}, valid_session
      response.should redirect_to(gp_diagnoses_url)
    end
  end

end
