require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PanicAlarmsController do

  # This should return the minimal set of attributes required to create a valid
  # PanicAlarm. As you add validations to PanicAlarm, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PanicAlarmsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all panic_alarms as @panic_alarms" do
      panic_alarm = PanicAlarm.create! valid_attributes
      get :index, {}, valid_session
      assigns(:panic_alarms).should eq([panic_alarm])
    end
  end

  describe "GET show" do
    it "assigns the requested panic_alarm as @panic_alarm" do
      panic_alarm = PanicAlarm.create! valid_attributes
      get :show, {:id => panic_alarm.to_param}, valid_session
      assigns(:panic_alarm).should eq(panic_alarm)
    end
  end

  describe "GET new" do
    it "assigns a new panic_alarm as @panic_alarm" do
      get :new, {}, valid_session
      assigns(:panic_alarm).should be_a_new(PanicAlarm)
    end
  end

  describe "GET edit" do
    it "assigns the requested panic_alarm as @panic_alarm" do
      panic_alarm = PanicAlarm.create! valid_attributes
      get :edit, {:id => panic_alarm.to_param}, valid_session
      assigns(:panic_alarm).should eq(panic_alarm)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PanicAlarm" do
        expect {
          post :create, {:panic_alarm => valid_attributes}, valid_session
        }.to change(PanicAlarm, :count).by(1)
      end

      it "assigns a newly created panic_alarm as @panic_alarm" do
        post :create, {:panic_alarm => valid_attributes}, valid_session
        assigns(:panic_alarm).should be_a(PanicAlarm)
        assigns(:panic_alarm).should be_persisted
      end

      it "redirects to the created panic_alarm" do
        post :create, {:panic_alarm => valid_attributes}, valid_session
        response.should redirect_to(PanicAlarm.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved panic_alarm as @panic_alarm" do
        # Trigger the behavior that occurs when invalid params are submitted
        PanicAlarm.any_instance.stub(:save).and_return(false)
        post :create, {:panic_alarm => {}}, valid_session
        assigns(:panic_alarm).should be_a_new(PanicAlarm)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PanicAlarm.any_instance.stub(:save).and_return(false)
        post :create, {:panic_alarm => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested panic_alarm" do
        panic_alarm = PanicAlarm.create! valid_attributes
        # Assuming there are no other panic_alarms in the database, this
        # specifies that the PanicAlarm created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PanicAlarm.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => panic_alarm.to_param, :panic_alarm => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested panic_alarm as @panic_alarm" do
        panic_alarm = PanicAlarm.create! valid_attributes
        put :update, {:id => panic_alarm.to_param, :panic_alarm => valid_attributes}, valid_session
        assigns(:panic_alarm).should eq(panic_alarm)
      end

      it "redirects to the panic_alarm" do
        panic_alarm = PanicAlarm.create! valid_attributes
        put :update, {:id => panic_alarm.to_param, :panic_alarm => valid_attributes}, valid_session
        response.should redirect_to(panic_alarm)
      end
    end

    describe "with invalid params" do
      it "assigns the panic_alarm as @panic_alarm" do
        panic_alarm = PanicAlarm.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PanicAlarm.any_instance.stub(:save).and_return(false)
        put :update, {:id => panic_alarm.to_param, :panic_alarm => {}}, valid_session
        assigns(:panic_alarm).should eq(panic_alarm)
      end

      it "re-renders the 'edit' template" do
        panic_alarm = PanicAlarm.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PanicAlarm.any_instance.stub(:save).and_return(false)
        put :update, {:id => panic_alarm.to_param, :panic_alarm => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested panic_alarm" do
      panic_alarm = PanicAlarm.create! valid_attributes
      expect {
        delete :destroy, {:id => panic_alarm.to_param}, valid_session
      }.to change(PanicAlarm, :count).by(-1)
    end

    it "redirects to the panic_alarms list" do
      panic_alarm = PanicAlarm.create! valid_attributes
      delete :destroy, {:id => panic_alarm.to_param}, valid_session
      response.should redirect_to(panic_alarms_url)
    end
  end

end
