require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SwDiariesController do

  # This should return the minimal set of attributes required to create a valid
  # SwDiary. As you add validations to SwDiary, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SwDiariesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all sw_diaries as @sw_diaries" do
      sw_diary = SwDiary.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sw_diaries).should eq([sw_diary])
    end
  end

  describe "GET show" do
    it "assigns the requested sw_diary as @sw_diary" do
      sw_diary = SwDiary.create! valid_attributes
      get :show, {:id => sw_diary.to_param}, valid_session
      assigns(:sw_diary).should eq(sw_diary)
    end
  end

  describe "GET new" do
    it "assigns a new sw_diary as @sw_diary" do
      get :new, {}, valid_session
      assigns(:sw_diary).should be_a_new(SwDiary)
    end
  end

  describe "GET edit" do
    it "assigns the requested sw_diary as @sw_diary" do
      sw_diary = SwDiary.create! valid_attributes
      get :edit, {:id => sw_diary.to_param}, valid_session
      assigns(:sw_diary).should eq(sw_diary)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SwDiary" do
        expect {
          post :create, {:sw_diary => valid_attributes}, valid_session
        }.to change(SwDiary, :count).by(1)
      end

      it "assigns a newly created sw_diary as @sw_diary" do
        post :create, {:sw_diary => valid_attributes}, valid_session
        assigns(:sw_diary).should be_a(SwDiary)
        assigns(:sw_diary).should be_persisted
      end

      it "redirects to the created sw_diary" do
        post :create, {:sw_diary => valid_attributes}, valid_session
        response.should redirect_to(SwDiary.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sw_diary as @sw_diary" do
        # Trigger the behavior that occurs when invalid params are submitted
        SwDiary.any_instance.stub(:save).and_return(false)
        post :create, {:sw_diary => {}}, valid_session
        assigns(:sw_diary).should be_a_new(SwDiary)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SwDiary.any_instance.stub(:save).and_return(false)
        post :create, {:sw_diary => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sw_diary" do
        sw_diary = SwDiary.create! valid_attributes
        # Assuming there are no other sw_diaries in the database, this
        # specifies that the SwDiary created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SwDiary.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => sw_diary.to_param, :sw_diary => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested sw_diary as @sw_diary" do
        sw_diary = SwDiary.create! valid_attributes
        put :update, {:id => sw_diary.to_param, :sw_diary => valid_attributes}, valid_session
        assigns(:sw_diary).should eq(sw_diary)
      end

      it "redirects to the sw_diary" do
        sw_diary = SwDiary.create! valid_attributes
        put :update, {:id => sw_diary.to_param, :sw_diary => valid_attributes}, valid_session
        response.should redirect_to(sw_diary)
      end
    end

    describe "with invalid params" do
      it "assigns the sw_diary as @sw_diary" do
        sw_diary = SwDiary.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SwDiary.any_instance.stub(:save).and_return(false)
        put :update, {:id => sw_diary.to_param, :sw_diary => {}}, valid_session
        assigns(:sw_diary).should eq(sw_diary)
      end

      it "re-renders the 'edit' template" do
        sw_diary = SwDiary.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SwDiary.any_instance.stub(:save).and_return(false)
        put :update, {:id => sw_diary.to_param, :sw_diary => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sw_diary" do
      sw_diary = SwDiary.create! valid_attributes
      expect {
        delete :destroy, {:id => sw_diary.to_param}, valid_session
      }.to change(SwDiary, :count).by(-1)
    end

    it "redirects to the sw_diaries list" do
      sw_diary = SwDiary.create! valid_attributes
      delete :destroy, {:id => sw_diary.to_param}, valid_session
      response.should redirect_to(sw_diaries_url)
    end
  end

end
